---
- name: Update dnf package cache
  ansible.builtin.dnf:
    update_cache: true

- name: Install base packages
  ansible.builtin.dnf:
    name: "{{ common_packages }}"
    state: present

- name: Set system timezone
  community.general.timezone:
    name: "{{ common_timezone }}"

- name: Create dedicated non-root system user
  ansible.builtin.user:
    name: "{{ common_system_user }}"
    system: true
    shell: /usr/sbin/nologin
    create_home: false
