prometheus_version: "3.14.0"
prometheus_checksum: "sha256:f665c6da19eb7ba399c915d30c7d9793c9b417bf8a749b504bc470678631478d"
prometheus_release_url: "https://github.com/prometheus/prometheus/releases/download"

prometheus_system_user: prometheus
prometheus_system_group: prometheus

prometheus_download_dir: /tmp/prometheus_install
prometheus_bin_path: /usr/local/bin/prometheus
prometheus_promtool_path: /usr/local/bin/promtool
prometheus_config_dir: /etc/prometheus
prometheus_data_dir: /var/lib/prometheus

prometheus_port: 9090
prometheus_scrape_interval: 15s

prometheus_scrape_targets:
  - job_name: prometheus
    targets:
      - "localhost:9090"
  - job_name: node
    targets:
      - "localhost:9100"
